// npm run build       plugin-scoped QVAC worker bundle from qvac.config.json (req 6.2.1)
//                     plus a tree-shaken, minified bundle of our own code (req 6.2.2)
// npm run build:full  the same with every built-in plugin first, then writes
//                     docs/bundle-size.md comparing the two
import { bundleSdk } from '@qvac/sdk/commands'
import { build } from 'esbuild'
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const host = `${process.platform}-${process.arch}`
const size = (p) => (!existsSync(p) ? 0 : statSync(p).isDirectory() ? readdirSync(p).reduce((n, e) => n + size(join(p, e)), 0) : statSync(p).size)
const mb = (b) => `${(b / 1024 ** 2).toFixed(1)} MB`

// One worker bundle plus the native addons it pulls in, sized for every host
// the SDK ships prebuilds for and for this host alone.
const variant = async (label, configPath) => {
  const r = await bundleSdk({ projectRoot: root, configPath, quiet: true })
  const addons = r.addons.filter((a) => a.startsWith('@qvac/'))
  const pkg = (a) => join(root, 'node_modules', a)
  const oneHost = (a) => size(pkg(a)) - size(join(pkg(a), 'prebuilds')) + size(join(pkg(a), 'prebuilds', host))
  return {
    label,
    plugins: r.plugins.length,
    addons,
    worker: size(r.bundlePath),
    allHosts: addons.reduce((n, a) => n + size(pkg(a)), 0),
    thisHost: addons.reduce((n, a) => n + oneHost(a), 0),
  }
}

const full = process.argv.includes('--full')
mkdirSync(join(root, 'dist'), { recursive: true })
const rows = []
if (full) {
  writeFileSync(join(root, 'dist', 'qvac.config.full.json'), '{}\n')
  rows.push(await variant('full SDK', 'dist/qvac.config.full.json'))
}
// Scoped goes last so qvac/ is left holding the bundle serve would ship with.
rows.push(await variant('plugin-scoped', 'qvac.config.json'))

await build({
  entryPoints: [join(root, 'index.js')],
  bundle: true,
  minify: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  outfile: join(root, 'dist', 'meridian-assistant.mjs'),
  // Native addons and the worker bundle above load at runtime.
  external: ['@qvac/*', '@lancedb/*', 'node:*'],
  logLevel: 'warning',
})
const app = size(join(root, 'dist', 'meridian-assistant.mjs'))

const table = [
  `| Build | Plugins | Worker bundle | Native addons, all hosts | Native addons, ${host} |`,
  '|---|---|---|---|---|',
  ...rows.map((r) => `| ${r.label} | ${r.plugins} | ${mb(r.worker)} | ${mb(r.allHosts)} | ${mb(r.thisHost)} |`),
].join('\n')

console.log(`\n${table}\n\nApplication code, tree-shaken and minified: ${mb(app)}`)
console.log(`Scoped addons: ${rows.at(-1).addons.join(', ')}`)

if (full) {
  const [f, s] = rows
  const cut = (a, b) => `${((1 - b / a) * 100).toFixed(0)}%`
  writeFileSync(join(root, 'docs', 'bundle-size.md'), `# Bundle size report

Generated by \`npm run build:full\` on ${host}. Model weights are excluded:
they are fetched after install (req 1.2), not shipped in the installer.

${table}

Application code (\`dist/meridian-assistant.mjs\`, esbuild, tree-shaken,
minified): **${mb(app)}**.

## Reading it

- **Worker bundle** is the JavaScript the Bare worker runs, generated by
  \`bundleSdk\` from the \`plugins\` array in \`qvac.config.json\`. Scoping cuts it
  by ${cut(f.worker, s.worker)}.
- **Native addons** are the llama.cpp, whisper.cpp and TTS binaries the
  plugins load. Scoping to the ${s.addons.length} packages we use cuts the
  all-hosts footprint by ${cut(f.allHosts, s.allHosts)}; keeping only this host's
  prebuilds brings what an installer for this platform carries to
  **${mb(s.thisHost)}**, ${cut(f.allHosts, s.thisHost)} less than the full SDK with every
  platform's binaries.
- Scoped addons: ${s.addons.map((a) => `\`${a}\``).join(', ')}.

The last column is the number for the IT lead: what an MDM push for one
platform contains, before weights.
`)
  console.log('wrote docs/bundle-size.md')
}
