// Opt in with `npm run test:e2e` after `npm run models:fetch`.
// Speech is generated by our own TTS so the suite needs no audio fixtures.
process.env.MERIDIAN_IDLE_UNLOAD_MS ??= '50'

import assert from 'node:assert/strict'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { after, before, describe, it } from 'node:test'
import { pcmToWav, wavToFloat32 } from '../../src/audio/wav.js'
import { squareOnWhite } from '../helpers/png.js'

const enabled = process.env.MERIDIAN_E2E === '1'
const quiet = { info: () => {}, warn: () => {}, error: () => {} }
const settled = () => new Promise((resolve) => setTimeout(resolve, 400))

describe('voice and vision', { skip: enabled ? false : 'set MERIDIAN_E2E=1 to run' }, () => {
  let runtime
  let dir

  const say = async (text, options = {}) => {
    const rate = options.outputSampleRate ?? 24_000
    const wav = pcmToWav(await runtime.speak(text, { language: 'en', ...options }), rate)
    const path = join(dir, `${Math.random().toString(36).slice(2)}.wav`)
    await writeFile(path, wav)
    return { path, wav }
  }

  before(async () => {
    const { createRuntime } = await import('../../src/runtime/index.js')
    runtime = createRuntime({ log: quiet })
    await runtime.start()
    dir = await mkdtemp(join(tmpdir(), 'meridian-e2e-'))
  })

  after(async () => {
    await runtime?.stop()
    await rm(dir, { recursive: true, force: true })
  })

  // 4.1 — more than one input language, detected rather than declared.
  for (const [language, text, expected] of [
    ['en', 'The ServoDrive X4 lead time is six weeks.', /lead time/i],
    ['es', 'El plazo de entrega del ServoDrive X4 es de seis semanas.', /plazo de entrega/i],
    // Cyrillic is what Supertonic 2 refused to speak at all. No Latin brand
    // name in it, and only the stem is checked: whisper-tiny on S drops words.
    ['ru', 'Срок поставки шесть недель.', /поставк/i],
  ]) {
    it(`transcribes ${language} without being told the language`, async () => {
      const { path } = await say(text, { language })
      assert.match(String(await runtime.transcribe(path)), expected)
    })
  }

  // 4.1.2 — the same sentence fed in as it would arrive from a microphone.
  it('transcribes a live stream chunk by chunk', async () => {
    const { wav } = await say('The lead time for the ServoDrive X4 is six weeks.', { outputSampleRate: 16_000 })
    const { samples } = wavToFloat32(wav)
    const { session, close } = await runtime.transcribeStream()
    const heard = []
    const reading = (async () => { for await (const piece of session) heard.push(String(piece)) })()

    for (let at = 0; at < samples.length; at += 8_000) session.write(Buffer.from(samples.slice(at, at + 8_000).buffer))
    session.end()
    await reading
    close()

    assert.match(heard.join(' '), /lead time/i)
  })

  // 4.3 — the model answers from the image, not from the wording of the question.
  it('answers about an image it was given, not about the prompt', async () => {
    const asked = []
    for (const [name, rgb] of [['green', [20, 180, 60]], ['blue', [30, 60, 220]]]) {
      const path = join(dir, `${name}.png`)
      await writeFile(path, squareOnWhite(256, rgb))
      asked.push(String(await runtime.look({
        prompt: 'What is the dominant colour in this image? Answer with one word.',
        imagePath: path,
        generationParams: { temp: 0, seed: 1, predict: 12 },
      })).toLowerCase())
    }

    assert.match(asked[0], /green/)
    assert.match(asked[1], /blue/)
  })

  it('gives the memory back once speech and vision go quiet', async () => {
    await runtime.transcribe((await say('Stock check.')).path)
    await settled()

    const roles = runtime.snapshot().models.map((model) => model.role)
    assert.deepEqual(roles.sort(), ['chat', 'embed'], 'only the resident models should still be loaded')
  })
})
